using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration.AdminEventLog;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Administration.UI.EventLog;

[GenerateTypedNameReferences]
public sealed partial class AdminEventLogWindow : FancyWindow
{
    [Dependency] private ILocalizationManager _localization = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    public AdminEventLogWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RoundSpinBox.IsValid = i => i > 0 && i <= CurrentRound;
        RoundSpinBox.ValueChanged += RoundSpinBoxChanged;
        RoundSpinBox.InitDefaultButtons();

        CategoryOption.AddItem(_localization.GetString("admin-event-category-none"), -1);

        var eventCategories = _protoMan.EnumeratePrototypes<EventCategoryPrototype>().ToList();
        var index = 0;
        foreach (var eventCategory in eventCategories)
        {
            CategoryOption.AddItem(_localization.GetString(eventCategory.Title), index);
            CategoryOption.SetItemMetadata(index, eventCategory.ID);
            index++;
        }

        CategoryOption.OnItemSelected += EventCategorySelected;

        EventTextEdit.Placeholder = new Rope.Leaf(_localization.GetString("admin-event-description-placeholder"));
        EventTextEdit.OnTextChanged += EventTextChanged;
        SendEventLog.Disabled = true; // no text, so can't send it yet.

        ResetRoundButton.OnPressed += ResetRoundPressed;
    }

    private int CurrentRound { get; set; }
    private bool AllowNoneCategory { get; set; }

    public ProtoId<EventCategoryPrototype>? EventCategory;

    public void SetAllowNoneCategory(bool value)
    {
        if (AllowNoneCategory == value)
            return;

        AllowNoneCategory = value;
        UpdateCategoryOption();
        UpdateSendButton();
    }

    public void SetCurrentRound(int round)
    {
        CurrentRound = round;
        ResetRoundButton.Text = Loc.GetString("admin-event-round-reset-with-id", ("id", round));
        UpdateResetButton();
    }

    public void SetRoundSpinBox(int round)
    {
        RoundSpinBox.Value = round;
        UpdateResetButton();
    }

    private void RoundSpinBoxChanged(ValueChangedEventArgs args)
    {
        UpdateResetButton();
    }

    private void EventCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        EventCategory = args.Id == -1
            ? (ProtoId<EventCategoryPrototype>?)null
            : new ProtoId<EventCategoryPrototype>((string)args.Button.GetItemMetadata(args.Id)!);

        CategoryOption.SelectId(args.Id);
        UpdateSendButton();
    }

    private void EventTextChanged(TextEdit.TextEditEventArgs args)
    {
        UpdateSendButton();
    }

    private void ResetRoundPressed(ButtonEventArgs args)
    {
        RoundSpinBox.Value = CurrentRound;
    }

    private void UpdateResetButton()
    {
        ResetRoundButton.Disabled = RoundSpinBox.Value == CurrentRound;
    }

    private void UpdateCategoryOption()
    {
        CategoryOption.SetItemDisabled(-1, !AllowNoneCategory);
    }

    private void UpdateSendButton()
    {
        var eventText = Rope.Collapse(EventTextEdit.TextRope).TrimStart();

        SendEventLog.Disabled =
            string.IsNullOrEmpty(eventText) ||
            !AllowNoneCategory && CategoryOption.SelectedId == -1;
    }
}
